
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAkhir = new javax.swing.JComboBox<>();
        jAwal = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jJenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTanggal = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDuduk = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        bClear = new javax.swing.JButton();
        bLihat = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bBeli1 = new javax.swing.JButton();
        rd23 = new javax.swing.JRadioButton();
        rd6 = new javax.swing.JRadioButton();
        rd15 = new javax.swing.JRadioButton();
        rd20 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lengkapi Data Dibawah Ini!"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaActionPerformed(evt);
            }
        });
        jPanel4.add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 165, 30));

        jLabel1.setText("Nama Pemesan");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("No. ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDActionPerformed(evt);
            }
        });
        jPanel4.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        jLabel4.setText("Stasiun Awal");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setText("Stasiun Akhir");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jAkhir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yogyakarta", "Semarang", "Solo" }));
        jAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAkhirActionPerformed(evt);
            }
        });
        jPanel4.add(jAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 30));

        jAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blitar", "Malang", "Surabaya" }));
        jAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAwalActionPerformed(evt);
            }
        });
        jPanel4.add(jAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Jenis Kereta");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "Bisnis", "Eksekutif" }));
        jPanel3.add(jJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        jLabel7.setText("Tanggal Berangkat");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel3.add(jTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        jLabel10.setText("Tempat Duduk");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel11.setText("Waktu Kereta");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        jPanel3.add(jDuduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 30));

        jLabel12.setText("Harga");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jHarga.setEditable(false);
        jPanel3.add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 30));

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel3.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 30));

        bLihat.setText("Lihat >>");
        bLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLihatActionPerformed(evt);
            }
        });
        jPanel3.add(bLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, 30));

        bExit.setText("Keluar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel3.add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 70, 30));

        bBeli1.setText("Beli");
        bBeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBeli1ActionPerformed(evt);
            }
        });
        jPanel3.add(bBeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 30));

        buttonGroup1.add(rd23);
        rd23.setText("23.00");
        jPanel3.add(rd23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        buttonGroup1.add(rd6);
        rd6.setText("06.00");
        jPanel3.add(rd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        buttonGroup1.add(rd15);
        rd15.setText("15.00");
        jPanel3.add(rd15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        buttonGroup1.add(rd20);
        rd20.setText("20.00");
        jPanel3.add(rd20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 240, 380));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Petunjuk"));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Lengkapi data diri \n2. Pilih Kereta dan Waktu\n3. Klik Tombol 'Beli'\n4. Klik Tombol 'Lihat' jika anda\n   ingin melihat tabel pembeli");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 280, 160));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ya.png"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setIconTextGap(0);
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 202));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 210, 190));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("PT. KERETA API INDONESIA ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 280, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("kontak_pelanggan@kereta-api.co.id");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("JL. Perintis Kemerdekaan No. 1 Bandung 40117  ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Telp. 121 / 021 121");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Fax (022) 4203342");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(556, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaActionPerformed

    private void jIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDActionPerformed

    private void jAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAkhirActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        jNama.setText("");
        jID.setText("");
        jTanggal.setDate(null);
        buttonGroup1.clearSelection();
        jHarga.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bBeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBeli1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jTanggal.getDate());
        String waktu="";
        String awal = jAwal.getSelectedItem().toString();
        String akhir = jAkhir.getSelectedItem().toString();
        String jenis = jJenis.getSelectedItem().toString();
        String duduk = jDuduk.getSelectedItem().toString();
        if (rd6.isSelected()){
            waktu = "06.00";
        } else if (rd15.isSelected()){
            waktu = "15.00";
        } else if (rd20.isSelected()){
            waktu = "20.00";
        } else{
            waktu = "23.00";
        }
        
      
        if(jNama.getText().equals("") || jID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Pastikan Data Anda Lengkap!", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO penumpang VALUES('"+jNama.getText()+"', '"+jID.getText()+"','"+jAwal.getSelectedItem()+"',"
                    + "'"+jAkhir.getSelectedItem()+"', '"+tanggal+"', '"+jJenis.getSelectedItem()+"','"+tanggal+"', '"+jDuduk.getSelectedItem()+"', '"+jHarga.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Selamat! Data telah diambahkan", "SUKSES",
                    JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambah", "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        }
        
        
        
        
    }//GEN-LAST:event_bBeli1ActionPerformed

    private void jAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAwalActionPerformed
        // TODO add your handling code here:
        if (jAwal.getSelectedItem().equals("Blitar")){
            jHarga.setText("150.000");
        } else if(jAwal.getSelectedItem().equals("Malang")){
            jHarga.setText("160.000");
        }else if(jAwal.getSelectedItem().equals("Surabaya")){
            jHarga.setText("170.000");
        }
    }//GEN-LAST:event_jAwalActionPerformed

    private void bLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLihatActionPerformed
        new Tabel().show();
            this.dispose();
    }//GEN-LAST:event_bLihatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBeli1;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bLihat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jAkhir;
    private javax.swing.JComboBox<String> jAwal;
    private javax.swing.JComboBox<String> jDuduk;
    private javax.swing.JTextField jHarga;
    private javax.swing.JTextField jID;
    private javax.swing.JComboBox<String> jJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jTanggal;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rd15;
    private javax.swing.JRadioButton rd20;
    private javax.swing.JRadioButton rd23;
    private javax.swing.JRadioButton rd6;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
       String kolom[] = {"Nama","ID","StasiunAwal","StasiunAkhir","Jenis","Tanggal","Waktu","TempatDuduk","Harga"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM `penumpang`";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String Nama = rs.getString(1);
               String ID = rs.getString(2);
               String StasiunAwal = rs.getString(3);
               String StasiunAkhir = rs.getString(4);
               String Jenis = rs.getString(3);
               String Tanggal = rs.getString(4);
               String Waktu = "";
               if("06.00".equals(rs.getString(3))){
                   Waktu = "06.00";
               }else if("15.00".equals(rs.getString(4))){
                   Waktu = "15.00";
               }else if("20.00".equals(rs.getString(5))){
                   Waktu = "20.00";
               }else {
                   Waktu = "23.00";
               }
               String TempatDuduk = rs.getString(6);
               String Harga = rs.getString(7);
               String data[] = {Nama,ID,StasiunAwal,StasiunAkhir,Jenis,Tanggal,Waktu,TempatDuduk,Harga};
               dtm.addRow(data);
           }
       } catch (SQLException ex) { 
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
}




